### PR TITLE
Update tour and add logo

### PR DESCRIPTION
**Pull request by czackl**

### CODE REVIEW

**Comment by czackl** [comment]
I do not get the pre-commit issue. Can we delete this function @alex-d13 @LorenzoMerotto? This was commented out somehow for testing.

**Comment by LorenzoMerotto** [comment]
Wait which function are you referring to? Can you maybe link the code?
 I don't understand where the error is coming from either

**Comment by czackl** [comment]
It was an old benchmarking function. Removed it. It was commented out "for testing", but i guess it is not needed anymore.

**Comment by czackl** [comment]
Any further comments? feel free to merge :)

**Pull request merged**
